/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package curso.java.basico;

public class HelloWorld {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new HelloWorld().getGreeting());
    }
}
