/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package curso.java.basico;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       HelloWorld classUnderTest = new HelloWorld();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
